apiVersion: apps/v1
kind: Deployment
metadata:
  name: chaos-2-staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chaos2-api
  template:
    metadata:
      labels:
        app: chaos2-api
    spec:
      containers:
        - name: chaos2
          image: eu.gcr.io/yotta-san-ml3/chaos-2:staging
          imagePullPolicy: Always
          volumeMounts:
            - name: config-vol
              mountPath: "/config"
              readOnly: True
      volumes:
        - name: config-vol
          configMap:
            name: chaos-apiconfig-2
