apiVersion: v1
kind: Service
metadata:
  name: chaos-2-loadbalancer
spec:
  selector:
    app: chaos2-api-staging
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer
