"""
    Column names from input files
"""

# Client data columns 
LAST_CONTACT_DATE = 'DATE'
AGE = 'AGE'
JOB_TYPE = 'JOB_TYPE'
MARITAL_STATUS = 'STATUS'
EDUCATION = 'EDUCATION'
HAS_DEFAULT = 'HAS_DEFAULT'
ACCOUNT_BALANCE = 'BALANCE'
HAS_HOUSING_LOAN = 'HAS_HOUSING_LOAN'
HAS_PERSO_LOAN = 'HAS_PERSO_LOAN'
COMMUNICATION_TYPE = 'CONTACT'
LAST_CONTACT_DURATION = 'DURATION_CONTACT'
NB_CONTACTS_CURRENT_CAMPAIGN = 'NB_CONTACT'
NB_DAYS_LAST_CONTACT = 'NB_DAY_LAST_CONTACT'
NB_CONTACTS_BEFORE_CAMPAIGN = 'NB_CONTACT_LAST_CAMPAIGN'
RESULT_LAST_CAMPAIGN = 'RESULT_LAST_CAMPAIGN'
EMPLOYMENT_VARIATION_RATE = 'EMPLOYMENT_VARIATION_RATE'
IDX_CONSUMER_PRICE = 'IDX_CONSUMER_PRICE'
IDX_CONSUMER_CONFIDENCE = 'IDX_CONSUMER_CONFIDENCE'
HAS_SUBSCRIBED = 'SUBSCRIPTION'

# Socio-economic data columns
END_MONTH = 'DATE'
EMPLOYMENT_VARIATION_RATE = 'EMPLOYMENT_VARIATION_RATE'
INFLATION_RATE = 'IDX_PRICE_CONSUMER'
CONSUMERS_ECONOMIC_CONFIDENCE = 'IDX_CONSUMER_CONFIDENCE'

MERGER_FIELD = 'YEAR-MONTH'
TARGET = HAS_SUBSCRIBED
